import "@fortawesome/fontawesome-free/css/all.min.css";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import localFont from "next/font/local";
import "react-toastify/dist/ReactToastify.css";
import { CartProvider } from "./_components/CartContext";
import ProductLoader from "./_components/ProductLoader";
import "./_styles/globals.module.css";

const vazirMatn = localFont({
  src: "../public/fonts/webfonts/Vazirmatn-FD-Medium.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={vazirMatn.className}>
        <SessionProvider>
          <ProductLoader>
            <CartProvider>{children}</CartProvider>
          </ProductLoader>
        </SessionProvider>
      </body>
    </html>
  );
}
